# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiDescription This endpoint registers a user. If you need to update a profile image, upload the profile image in the background using `/avatar` endpoint.
@apiVersion 1.0.0
@api {POST} api/v1/register Register
@apiGroup Auth
@apiParam {String} device_id Unique ID of the device
@apiParam {String} device_type Type of the device `APPLE` or `ANDROID`
@apiParam {String} [device_push_token] Unique push token for the device
@apiParam {String} first_name First name of user
@apiParam {String} last_name Last name of user
@apiParam {String} email Email address of user
@apiParam {String} phone Phone number in international format
@apiParam {String} date_of_birth Date of birth in YYYY/MM/DD format
@apiParam {String} password Password. Must be at least 8 characters.
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
@apiErrorExample {json} Error-Response / HTTP 422 Unprocessable Entity
{
					"message": "The email must be a valid email address.",
					"payload": {
						"errors": {
							"email": [
								"The email must be a valid email address."
							]
						}
					},
					"result": false
				}
###
# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiVersion 1.0.0
@api {POST} api/v1/login Login
@apiGroup Auth
@apiParam {String} device_id Unique ID of the device
@apiParam {String} device_type Type of the device `APPLE` or `ANDROID`
@apiParam {String} [device_push_token] Unique push token for the device
@apiParam {String} email Email
@apiParam {String} password Password
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
					"payload": {
						"id": 31,
						"uuid": "6dfb4b23-df73-49d1-90ab-a3118cc170ed",
						"name": "null",
						"last_name": "null",
						"email": "test@example.com",
						"avatar_url": null,
						"first_name": "null",
						"full_name": "null null",
						"access_token": "1540054802BbiqclNMqujaIgfGzRMjsdds8a9M4HvBxPg"
					},
					"message": "",
					"result": true
				}
###
# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiDescription Logout the user from current device
@apiVersion 1.0.0
@api {GET} api/v1/logout Logout
@apiGroup Auth
@apiUse default_headers
###
# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiVersion 1.0.0
@api {POST} api/v1/password/edit Update Password
@apiGroup Auth
@apiParam {String} password Password
@apiParam {String} current_password Current password
@apiParam {String} password_confirmation Password confirmation
@apiUse default_headers
###
