# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiDefine default_headers 
@apiVersion 1.0.0
@api {}  
@apiGroup Default_headers
@apiHeader {String} Accept Set to `application/json`
@apiHeader {String} x-api-key API Key
@apiHeader {String} x-access-token Unique user authentication token
###
