# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiDescription FAQs and answers
@apiVersion 1.0.0
@api {GET} api/v1/faqs FAQs
@apiGroup FAQs
@apiParam {Integer} q Page number
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
					"payload": {
						"Add your response here"
					},
					"message": "",
					"result": true
				}
###
