# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiVersion 1.0.0
@api {GET} api/v1/games List Games
@apiGroup Games
@apiParam {Integer} [p] Page number. Default will be 1
@apiParam {String} [status] Accepted values `active`. Default is `all`
@apiParam {String} [game_type] Accepted values `hole-18`, `hole-9`
@apiParam {String} [play_type] Accepted values `single`, `team`
@apiUse default_headers
###
# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiVersion 1.0.0
@api {POST} api/v1/games Create Game
@apiGroup Games
@apiParam {String} date Date in DD/Mon/YYYY format
@apiParam {String} time Time in HH:MM AA format
@apiParam {String} formatted_address Displayed name of the venue
@apiParam {String} [street] Address line 1
@apiParam {String} [street_2] Address line 2
@apiParam {String} [city] Time in HH:MM AA format
@apiParam {String} state Time in HH:MM AA format
@apiParam {String} country Name of country
@apiParam {String} country_iso_code ISO code of venue country
@apiParam {String} game_type Accepted values `hole-18`, `hole-9`
@apiParam {String} play_type Accepted values `single`, `team`
@apiParam {Integer} game_max_player_limit Total players for game
@apiParam {Integer} [team_max_player_limit] Required for `team` games
@apiParam {String} player_order Accepted values `auto`, `manual`
@apiParam {Boolean} has_wildcards Accepted values `true`, `false`
@apiParam {Boolean} has_animations Accepted values `true`, `false`
@apiUse default_headers
###
