# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiVersion 1.0.0
@api {GET} api/v1/leaderboard Get Rankings
@apiGroup Leaderboard
@apiParam {Integer} [p] Page number. Default will be 1
@apiParam {String} [country_code] ISO Country code
@apiParam {String} [state] State
@apiUse default_headers
###
