# ************************************************* #
#       AUTO-GENERATED. DO NOT EDIT THIS FILE.      #
# ************************************************* #
#    Create your files in `resources/docs/manual`   #
# ************************************************* #
###
@apiDescription Claim an order ID and become a premium user
@apiVersion 1.0.0
@api {POST} api/v1/claim-order Claim an Order
@apiGroup Orders
@apiParam {String} order_id Order ID to claim
@apiUse default_headers
###
